### ISSUE TITLE
"convertFromHTML" not support tag "img" ?  "draftToHtml" was not friendly to "img"?

### ISSUE THREAD

**Issue by raisezhang** [jpuri/react-draft-wysiwyg#16] opened 2016-10-25 18:09 UTC
Hello  ~

Very thank you for your amazing writing component, thanks a lot!
But I found some problems in the process of use:

1："convertFromHTML" method does not support img tags！
Ex: 
`ContentState createFromBlockArray (convertFromHTML ('<p>123<img src="http://image.mmzhuli.com/e0bd1b1a-8a8c-4cec-b42e-1e9605594353?hjw=50&hjh=50"/><br/>1111</p> '))`
2, in the process of submitted data,"draftToHtml" method seems more parsing out a symbol
Ex: 
<img width="858" alt="qq20161026-0 2x" src="https://cloud.githubusercontent.com/assets/1481983/19698209/f6536016-9b20-11e6-9fd5-15841af314fc.png">

Thanks~   Really looking forward to receive your reply！

**Comment by jpuri** [comment] 2016-10-25 19:29
Hi @raisezhang,

Thanks a lot for checking out the library :)

1. `convertFromHTML` is method of draft-js library and not this library. As I know it supports only a set of html tags and attributes.

2. For converting draftjs editor state to HTML I am using this library: `https://github.com/jpuri/draftjs-to-html`. readme of the library details the supported conversions. Can you tell me the exact content of your editor which you are converting. It will help me in identifying the bug.

Thanks again,

**Comment by raisezhang** [comment] 2016-10-26 02:27
I mainly refer to [demo2](https://jpuri.github.io/react-draft-wysiwyg/#/demo2?_k = v5o7tp) and [demo4](https://jpuri.github.io/react-draft-wysiwyg/#/demo4?_k = PNBFCF) ! reference demo2 initialization data, reference demo4 implement custom style.

Question 1: I checked the draft-js, method seems to be no problem, but it is error when parsing img tags here~   you have any good recommendations? Mainly realize at the time of initialization data and contain img tags.

Question 2: the editor contains pictures and words, I need to cache HTML data on  method "onEditorChange" .  The screenshot below:

<img width="568" alt="qq20161026-0 2x" src="https://cloud.githubusercontent.com/assets/1481983/19710728/1a3ded24-9b63-11e6-9cef-bf7bb25bf7c9.png">

The code below:

```javascript
onEditorChange = (editorContent) => {
    this.setState({editorContent});
    if (this.props.onChange) {
      console.log(draftToHtml(editorContent));
      this.props.onChange(draftToHtml(editorContent));
    }
};
```
this will print 

``` html
<p>123<br>
</p>
><img src="http://xxx.jpg" style="float:none"/>
<p></p>
```

Thank you very much！

**Comment by raisezhang** [comment] 2016-10-26 05:55
And find some warning in the console!

``` javascript
warning.js:36 Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `e`, expected `object`.
```
``` javascript
warning.js:36 Warning: Failed prop type: Invalid prop `children` of type `string` supplied to `e`, expected `object`.
```
``` javascript
warning.js:36 Warning: Failed prop type: Invalid prop `children` of type `number` supplied to `e`, expected `object`.
```

Thanks  ^_^

**Comment by jpuri** [comment] 2016-10-26 05:56
ok I see somehow not replicating for me:
![screen shot 2016-10-26 at 11 24 15 am](https://cloud.githubusercontent.com/assets/2182307/19714848/eb9e28d8-9b6e-11e6-99a3-bab8139495a9.png)

Can you tell me exactly what changes you did in the editor like:
1. Uploaded image
2. Shift+Enter
3. Writing text...

**Comment by jpuri** [comment] 2016-10-26 05:57
Thx :)
Yep working on those warnings already. You can expect those to be fixed really soon.

**Comment by raisezhang** [comment] 2016-10-26 06:10
Is the ordinary operation， screenshot below：

**1、write some words**
![qq20161026-0](https://cloud.githubusercontent.com/assets/1481983/19715062/5f4f125e-9b85-11e6-8e2e-922941f69d86.png)
**2、click button pic  and paste url**
![qq20161026-1](https://cloud.githubusercontent.com/assets/1481983/19715073/6e32e98a-9b85-11e6-851c-0dae93bee3b0.png)
**3、click Add,  And  then …**
![qq20161026-2](https://cloud.githubusercontent.com/assets/1481983/19715111/9c7e1256-9b85-11e6-8a40-24bbf66a82db.png)

If only add images will appear this problem！

Thanks

**Comment by raisezhang** [comment] 2016-10-26 06:29
I'll try to in my local compile your demo, thanks a lot ~

**Comment by orditeck** [comment] 2016-11-12 03:56
I have the same warning.

`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See DraftEditorContents > p > ... > DraftEditorBlock > div.`

The problem is this `<p>`:

![](http://i.imgur.com/9dqniHn.png)

**Comment by orditeck** [comment] 2016-11-12 04:09
@raisezhang regarding the warning, see #45 & pull request #46 which fix this.

**Comment by raisezhang** [comment] 2016-11-12 04:44
Thanks  :)

**Comment by jpuri** [comment] 2016-11-23 18:05
@raisezhang: is there still something I can help you with.

**Comment by jpuri** [comment] 2016-11-23 19:17
Ok, I am closing the issue for now.

**Closed by jpuri** 2016-11-23 19:17 UTC
