### ISSUE TITLE
Modals closing prematurely

### ISSUE THREAD

**Issue by Fouppy** [jpuri/react-draft-wysiwyg#154] opened 2016-12-30 16:28 UTC
Hi,

Just a reminder for this issue, as it's closed: https://github.com/jpuri/react-draft-wysiwyg/issues/120

Thanks!

**Comment by jpuri** [comment] 2017-01-02 01:50
Thanks a lot @Fouppy

**Comment by ZeroCho** [comment] 2017-01-06 12:31
can find this problem in demo

**Comment by jpuri** [comment] 2017-01-08 18:49
@Fouppy, @ZeroCho : I will fix this on priority now.

**Comment by jpuri** [comment] 2017-01-09 03:30
Fixed in release `react-draft-wysiwyg@1.5.6`.

**Closed** 2017-01-09 03:31 UTC
Labels: bug

**Comment by Fouppy** [comment] 2017-01-09 09:38
Will try asap, thanks!

**Comment by Peterabsolon** [comment] 2017-05-15 14:31
I'm still experiencing this issue. Using 1.9.9

**Comment by jpuri** [comment] 2017-05-15 15:10
Hey @Peterabsolon , can you plz share may be a video. It seems to work well here: https://jpuri.github.io/react-draft-wysiwyg/#/demo. May be some event handling on your page is effecting it.

**Comment by Peterabsolon** [comment] 2017-05-16 14:28
@jpuri The issue is with the nested Modal, for example when you want to include a link. It opens up correctly, you can type something inside on of the inputs but as soon as you click (or tab) to the other input the whole modal closes.

There is no option to include Link in the example you linked.
