### ISSUE TITLE
uncaught TypeError: t.suggestionCallback is not a function

### ISSUE THREAD

**Issue by dderr** [jpuri/react-draft-wysiwyg#115] opened 2016-12-09 08:26 UTC
![image](https://cloud.githubusercontent.com/assets/585448/21042232/c6d38ad4-bdb5-11e6-954d-8b42370c9a45.png)

source:
{document.addEventListener("click",function(){t.editorFlag?t.editorFlag=!1:(t.closeAllModals(),t.suggestionCallback()

I believe react-draft-wysiwyg/js/src/event-handler/modals.js is calling 
  init = () => {
    document.addEventListener('click', () => { // eslint-disable-line no-undef
      if (!this.editorFlag) {
        this.closeAllModals();
// THIS undefined?
        this.suggestionCallback();
      } else {
        this.editorFlag = false;
      }
    });
  };

**Comment by jpuri** [comment] 2016-12-09 08:33
@dderr: I see this is caused by a recent change, I will fix it quick.

**Comment by jpuri** [comment] 2016-12-09 08:41
Version #1.3.1 in npm has the fix.

**Comment by dderr** [comment] 2016-12-09 09:35
Awesome.. Thx for the 20minute turn around time.

**Comment by jpuri** [comment] 2016-12-09 12:26
😄  closing the issue now.

**Closed by jpuri** 2016-12-09 12:26 UTC
